# -*- coding: utf-8 -*-
"""dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBNk9O5bOHD2mq9QpL7JQhxH5n5BRTku
"""

mydict = {'key1':'value1','key2':'value2'}
mydict['key1']

prices_lookup = {'apple':2.99,"oranges":1.99,'milk':5.80}
prices_lookup['apple']

d = {'k1':123,'k2':{0,1,2},'k3':{'insideK':100}}
d['k3']

d = {'key1': ['a','b','c']}
d

mylist = d['key1']
mylist

letter = mylist[2]
letter

letter.upper()

d['key1'][2].upper()

d = {'k1':100,'k2':200}
d

d['k3'] = 300
d

d.keys()

d.values()

d.items()
