# -*- coding: utf-8 -*-
"""tuples,setsandbooleans

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBNk9O5bOHD2mq9QpL7JQhxH5n5BRTku
"""

t = (1,2,3)

mylist = [1,2,3]
type(t)

type(mylist)

len(t)

t = ('a','a','b')
t.count('a')

t.index('a')

t.index('b')

t
mylist

mylist[0] = 'new'
mylist

t[0] = 'new' #tuples are immutable

myset = set()
myset

myset.add(1)
myset

myset.add(2)
myset

myset.add(2)
myset

mylist = [1,1,1,1,1,2,2,2,2,2,3,3,3,3]
myset.add(mylist)

True 
False
type(True)

1 > 2

1==1

set([1,1,2,3])

