# -*- coding: utf-8 -*-
"""pywrk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBNk9O5bOHD2mq9QpL7JQhxH5n5BRTku
"""

mylist = ['string',50,50.1]
len(mylist)

mylist = ['one','two','three']
mylist[0]

another_list = ['four','five']
mylist + another_list

new_list = mylist + another_list
new_list

new_list[0] = 'ONE ALL CAPS'
new_list

new_list.append('six')
new_list

new_list.pop()

new_list

new_list.pop(0)

new_list

new_list = ['a','e','x','c','d']
num_list = [4,1,8,3]

new_list.sort()
new_list

new_list.sort()
my_sorted_list = new_list
new_list

num_list

num_list.sort()

num_list

num_list.reverse()

num_list

