# -*- coding: utf-8 -*-
"""pywrk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBNk9O5bOHD2mq9QpL7JQhxH5n5BRTku
"""

name ='Sam'
last_letters = name[1:]
last_letters
last_letters = 'P' + last_letters

last_letters

x = 'Hello World'
x.split()

x = 'Hi this is a string'

x.split()

print('This is a string {}'.format('INSERTED'))

print('The {2} {1} {0}'.format('fox','brown','quick'))

print('The {q} {b} {f}'.format(f='fox',b='brown',q='quick'))

result = 100/777
print('The result was {r:1.2f}'.format(r=result))

name = 'Tony'
age = 34
print(f'{name} is {age} years old.') #f strings came in py 3.6,far more convenient.